export { default as hourglassesIcon } from './images/hourglasses.png'

// 枚(まい)
export { default as blanketIcon } from './images/mai/blanket.png'
export { default as paperIcon } from './images/mai/paper.png'
export { default as pizzaIcon } from './images/mai/pizza.png'
export { default as plateIcon } from './images/mai/plate.png'
export { default as shirtIcon } from './images/mai/shirt.png'
export { default as sliceOfBreadIcon } from './images/mai/slice-of-bread.png'
export { default as sweaterIcon } from './images/mai/sweater.png'

// 本(ほん)
export { default as flowerIcon } from './images/hon/flower.png'
export { default as pantsIcon } from './images/hon/pants.png'
export { default as penIcon } from './images/hon/pen.png'
export { default as ropeIcon } from './images/hon/rope.png'
export { default as tieIcon } from './images/hon/tie.png'
export { default as treeIcon } from './images/hon/tree.png'
export { default as umbrellaIcon } from './images/hon/umbrella.png'

// 匹(ひき)
export { default as catIcon } from './images/hiki/cat.png'
export { default as dogIcon } from './images/hiki/dog.png'
export { default as fishIcon } from './images/hiki/fish.png'
export { default as ladybirdIcon } from './images/hiki/ladybird.png'
export { default as mouseIcon } from './images/hiki/mouse.png'

// 台(だい)
export { default as bicycleIcon } from './images/dai/bicycle.png'
export { default as carIcon } from './images/dai/car.png'
export { default as laptopIcon } from './images/dai/laptop.png'
export { default as refrigeratorIcon } from './images/dai/refrigerator.png'
export { default as tvIcon } from './images/dai/tv.png'

// 箇(つ)
export { default as bellPepperIcon } from './images/tsu/bell-pepper.png'
export { default as cupIcon } from './images/tsu/cup.png'
export { default as orangeIcon } from './images/tsu/orange.png'
export { default as teddyBearIcon } from './images/tsu/teddy-bear.png'

// 日(にち)
export { default as calendar1Icon } from './images/nichi/calendar-1.png'
export { default as calendar2Icon } from './images/nichi/calendar-2.png'
export { default as calendar3Icon } from './images/nichi/calendar-3.png'
export { default as calendar4Icon } from './images/nichi/calendar-4.png'
export { default as calendar5Icon } from './images/nichi/calendar-5.png'
export { default as calendar6Icon } from './images/nichi/calendar-6.png'
export { default as calendar7Icon } from './images/nichi/calendar-7.png'
export { default as calendar8Icon } from './images/nichi/calendar-8.png'
export { default as calendar9Icon } from './images/nichi/calendar-9.png'
export { default as calendar10Icon } from './images/nichi/calendar-10.png'
export { default as calendar11Icon } from './images/nichi/calendar-11.png'
export { default as calendar12Icon } from './images/nichi/calendar-12.png'
export { default as calendar13Icon } from './images/nichi/calendar-13.png'
export { default as calendar14Icon } from './images/nichi/calendar-14.png'
export { default as calendar15Icon } from './images/nichi/calendar-15.png'
export { default as calendar16Icon } from './images/nichi/calendar-16.png'
export { default as calendar17Icon } from './images/nichi/calendar-17.png'
export { default as calendar18Icon } from './images/nichi/calendar-18.png'
export { default as calendar19Icon } from './images/nichi/calendar-19.png'
export { default as calendar20Icon } from './images/nichi/calendar-20.png'
export { default as calendar21Icon } from './images/nichi/calendar-21.png'
export { default as calendar22Icon } from './images/nichi/calendar-22.png'
export { default as calendar23Icon } from './images/nichi/calendar-23.png'
export { default as calendar24Icon } from './images/nichi/calendar-24.png'
export { default as calendar25Icon } from './images/nichi/calendar-25.png'
export { default as calendar26Icon } from './images/nichi/calendar-26.png'
export { default as calendar27Icon } from './images/nichi/calendar-27.png'
export { default as calendar28Icon } from './images/nichi/calendar-28.png'
export { default as calendar29Icon } from './images/nichi/calendar-29.png'
export { default as calendar30Icon } from './images/nichi/calendar-30.png'
export { default as calendar31Icon } from './images/nichi/calendar-31.png'